2019-05-27 12:15:27,242 ERROR: Exception on /explore [GET] [in /home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/fk/py/microblog/app/routes.py", line 141, in explore
    next_url=next_url, prev_url=prev_url)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fk/py/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/fk/py/microblog/app/templates/base.html", line 30, in top-level template code
    {%block content %}{% endblock %}
  File "/home/fk/py/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_post.html' %}
  File "/home/fk/py/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
UndefinedError: 'None' has no attribute 'avatar'
2019-05-27 12:17:55,944 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-27 12:18:19,925 ERROR: Exception on /explore [GET] [in /home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/fk/py/microblog/app/routes.py", line 141, in explore
    next_url=next_url, prev_url=prev_url)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fk/py/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/fk/py/microblog/app/templates/base.html", line 30, in top-level template code
    {%block content %}{% endblock %}
  File "/home/fk/py/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_post.html' %}
  File "/home/fk/py/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
UndefinedError: 'None' has no attribute 'avatar'
2019-05-27 12:18:49,178 ERROR: Exception on /explore [GET] [in /home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/fk/py/microblog/app/routes.py", line 141, in explore
    next_url=next_url, prev_url=prev_url)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fk/py/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/fk/py/microblog/app/templates/base.html", line 30, in top-level template code
    {%block content %}{% endblock %}
  File "/home/fk/py/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_post.html' %}
  File "/home/fk/py/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
UndefinedError: 'None' has no attribute 'avatar'
2019-05-27 12:18:56,552 ERROR: Exception on /explore [GET] [in /home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/fk/py/microblog/app/routes.py", line 141, in explore
    next_url=next_url, prev_url=prev_url)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fk/py/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/fk/py/microblog/app/templates/base.html", line 30, in top-level template code
    {%block content %}{% endblock %}
  File "/home/fk/py/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_post.html' %}
  File "/home/fk/py/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
UndefinedError: 'None' has no attribute 'avatar'
2019-05-27 12:22:37,752 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
